### ISSUE TITLE
Return a Single instead of Observable

### ISSUE THREAD

**Issue by veyndan** [Meisolsson/GitHubSdk#1]
For the Retrofit services, returning a Single instead of Observable improves the understanding behind what is returned i.e. exactly one element or an error. When using an Observable such a contract isn't explicit.

**Comment by Meisolsson** [comment]
This sounds like a good idea. Should really have read up on RxJava a bit more before doing this. But changing to Single sounds like the right way. 

Just one question:
Would this break any method calls or does Single and Observable have the same API (mostly)?

**Comment by veyndan** [comment]
It is fairly trivial to migrate from `Observable` to `Single`. Some operators are missing on `Single`, but purely because it doesn't make sense to have them e.g. `concatMap` is missing as having the stream emit the elements in order when there is only one element is redundant.

**Comment by Meisolsson** [comment]
Alright, if you have the time feel free to make a PR.
