### ISSUE TITLE
Use @NonNull when returning a list

### ISSUE THREAD

**Issue by veyndan** [Meisolsson/GitHubSdk#11]
Can't we just assume that when we are parsing a list in JSON that it'll return an empty list instead of null? Or is this a well known problem with the API that null is returned when an empty list should be returned?

If we changed the annotation from @Nullabe to @NonNull we can reduce the number of null checks required in PocketHub as we can now assume the returned object is non null which will increase the readability of the code.

**Comment by Meisolsson** [comment]
I think we can safely assume that there will always be an empty list returned. Biggest problem with the API is that the other values have no docuementation about being null or not. So the fact that most things have a `@Nullable` is becasuse of that.

**Comment by veyndan** [comment]
Awesome, I'll make a PR to annotate them `@NonNull`. Regarding the other values, I think if there is a sensible default value if the value is null then we can annotate them `@NonNull` as well.

**Comment by Meisolsson** [comment]
Had to add some list back as Nullable since they were, see a563c7341f76ee4c6ea11c29ff6d192fb0644285

**Comment by maniac103** [comment]
For request objects, marking all lists as NonNull also isn't correct, as passing null for optional items (such as issue assignees) is perfectly fine - see https://github.com/Meisolsson/GitHubSdk/pull/14/commits/888c7a3e0e728c60c10545ac94c8020514bcee0e in #14.
