### ISSUE TITLE
No release builds possible while using library

### ISSUE THREAD

**Issue by maniac103** [Meisolsson/GitHubSdk#28]
(Seemingly) since the update to newer Moshi etc. in 0.6.0, I can't build app release builds anymore while using the library. Error message is
```
Use of generics not allowed for java type at '<1>_<2>_<3>JsonAdapter' in line 31 of file '/home/daba/.gradle/caches/transforms-1/files-1.1/moshi-1.8.0.jar/221795ef4f1b7c58769787394fc98e4d/META-INF/proguard/moshi.pro'
```

This seems to be https://github.com/square/moshi/issues/738 ... I tried the [suggested workaround](https://github.com/square/moshi/issues/738#issuecomment-453024615) of upgrading Proguard, which got me a bit further, but then I get
```
com.meisolsson.githubsdk.model.Branch: can't find referenced class com.google.auto.value.AutoValue
com.meisolsson.githubsdk.model.ClientErrorResponse: can't find referenced class com.google.auto.value.AutoValue
```
(and many more of those)

Judging from the [AutoValue UG](https://github.com/google/auto/blob/master/value/userguide/index.md) it looks like one needs to pull in autovalue using 'api' instead of 'compile only', but I haven't managed to build the library that way yet.

Did you attempt a release build of an app using the library since the upgrade, and/or can you help in figuring this out?

**Comment by Meisolsson** [comment]
I have built a release with that version and released it. Not sure what is different between our builds here. I'll take a look later today.

**Comment by maniac103** [comment]
Just to be clear: I'm talking of a release build (including proguard) of an app using the library, not the library itself.

**Comment by Meisolsson** [comment]
Yeah, it's built on this commit https://github.com/pockethub/PocketHub/commit/ef9a1c31bedb49b4e57c69ab1a74a9f1fb1b0ff4 (Travis says if failed but thats not our code it's travis being weird)

**Comment by Meisolsson** [comment]
So I don't have a perfect answer here but a bit of info.

I can reproduce the issue, just needed to use ProGuard (been deactivated for a long time). And when testing the workaround I get the same error. So I tested a custom build of the library with the `api` change and I get different (weirder) errors.

I did try enabling R8 and that does the trick for me.

Sadly I can't really help you more here. The issue is more a ProGuard or Moshi problem.

**Comment by Meisolsson** [comment]
I guess since I can't find reference you might be able to do a keep for those classes.

**Comment by maniac103** [comment]
After upgrading to Android Studio 3.4 (with R8) this issue seems fixed, but a new one pops up instead: AS 3.4 wants Gradle 5.1, which [enforces API and implementation library separation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation), which in turn has a few implications:

- the dependency to JodaTime needs to become `api` (as it needs to be initialized by the lib user for the lib to work)
- same for rxjava (for `Single`) and retrofit (for `Response`)

I've tried adding the dependencies manually:
```

    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.5.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.5.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.6.0'
    implementation 'com.squareup.moshi:moshi:1.8.0'
    implementation 'io.reactivex.rxjava2:rxjava:2.1.10'
    implementation 'net.danlew:android.joda:2.9.5.1'
```

but am not getting weird issues that look like multiple lib versions are in play, such as `FormattedHtmlAdapter` being used to decode the `message` field in `ClientErrorResponse`, even though that field doesn't have a `FormattedHtml` annotation.

Could you check whether you get similar issues in PocketHub when updating to Gradle 5?

**Comment by Meisolsson** [comment]
Really sorry for this taking so long. Version 0.6.2 should have this fixed.

**Comment by Meisolsson** [comment]
Actually get 0.6.3 as the POM file was incorrec for 0.6.2
